---
- hosts: all
  become: true
  tasks:
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: run docker image
    command: sudo docker run -it -d -p 8888:8888 tarun3834/spring:1.4
  handlers:
  - name: run update
    apt:
      update_cache: yes
...
